export const login = () => {
  try {
  } catch (error) {
    console.error('Error when we tried to login', error);
  }
};

export const register = () => {
  try {
  } catch (error) {
    console.error('Error when we tried to login', error);
  }
};

export const logout = () => {
  try {
  } catch (error) {
    console.error('Error when we tried to login', error);
  }
};

export const recoveryPassword = (email: string) => {
  try {
  } catch (error) {
    console.error('Error when we tried to login', error);
  }
};
